---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(viridis)
library(plotly)
```


```{r}
nyc_airbnb = read_csv("nyc_airbnb.csv")
```


```{r}
set.seed(1)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

Inputs{.sidebar}{data-width=150} 
----------------------------------
description

Column {data-width=600}
-----------------------------------------------------------------------
### Chart A

```{r}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
          color = ~price, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
```