---
title: "Untitled"
output: html_document
---

My name is jeff and i make websites _with interactive graphics_ !!!


```{r}
library(tidyverse)
library(viridis)
library(plotly)
```



## Let's make some plots


```{r}
nyc_airbnb = read_csv("nyc_airbnb.csv")
```



```{r}
set.seed(1)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

```{r}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers", ## need ~ before variables
          color = ~price, alpha = 0.5)
```

```{r}
common_neighbourhood = 
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(nyc_airbnb, common_neighbourhood, by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")

```

## or using ggplotly to make basic plot to plotly

```{r}
box_neighbour = 
  inner_join(nyc_airbnb, common_neighbourhood, by = "neighbourhood") %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
    ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood), color = "blue") + 
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_neighbour)
    
  
```



```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
```
